---
name: CMake Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  # 1) Windows: build、打包并创建 Release
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Configure & Build (Windows)
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
        shell: bash

      - name: Package Windows ZIP
        run: |
          mkdir -p dist
          cp build/Release/*.exe dist/
          7z a MyCppProject-${{ env.VERSION }}-windows_x86_64.zip dist/*
        shell: bash

      - name: Create GitHub Release & upload Windows asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ env.VERSION }}
          files: MyCppProject-${{ env.VERSION }}-windows_x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  # 2) Linux: build、打包并上传资产
  build-linux:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        shell: bash

      - name: Install packaging tools
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev p7zip-full
        shell: bash

      - name: Configure & Build (Linux)
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
        shell: bash

      - name: Create .deb package
        run: |
          cmake --install build --prefix dist
          mkdir -p dist/DEBIAN
          echo "Package: mycppproject" > dist/DEBIAN/control
          echo "Version: ${{ env.VERSION }}" >> dist/DEBIAN/control
          echo "Architecture: amd64" >> dist/DEBIAN/control
          echo "Maintainer: You <you@example.com>" >> dist/DEBIAN/control
          echo "Description: My C++ Project" >> dist/DEBIAN/control
          dpkg-deb --build dist mycppproject_${{ env.VERSION }}_amd64.deb
        shell: bash

      - name: Package Linux ZIP
        run: 7z a MyCppProject-${{ env.VERSION }}-Linux_deb_x86_64.zip mycppproject_${{ env.VERSION }}_amd64.deb
        shell: bash

      - name: Upload Linux asset
        uses: softprops/action-gh-release@v2
        with:
          create_release: false
          files: MyCppProject-${{ env.VERSION }}-Linux_deb_x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  # 3) macOS: build、打包并上传资产
  build-macos:
    needs: build-windows
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        shell: bash

      - name: Configure & Build (macOS)
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
        shell: bash

      - name: Package macOS ZIP
        run: |
          mkdir -p dist
          cp build/MyCppProject dist/
          7z a MyCppProject-${{ env.VERSION }}-macOS_x86_64.zip dist/*
        shell: bash

      - name: Upload macOS asset
        uses: softprops/action-gh-release@v2
        with:
          create_release: false
          files: MyCppProject-${{ env.VERSION }}-macOS_x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
