---
name: CMake Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Get version from tag
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: |
          mkdir -p dist
          cp build/Release/*.exe dist/
          cd dist
          7z a ../MyCppProject-${{ env.VERSION }}.zip *

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: MyCppProject-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
