name: Build C++ Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up CMake for Ubuntu
      - name: Install CMake (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      # Set up CMake for Windows
      - name: Install CMake (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake
          choco install visualstudio2019buildtools

      # Set up CMake for macOS
      - name: Install CMake (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install cmake

      # Configure and build the project
      - name: Configure and build
        run: |
          cmake .
          cmake --build .

      # Run tests (if applicable)
      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        run: |
          ./MyCppProject

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: |
          .\MyCppProject.exe

      - name: Run tests (macOS)
        if: runner.os == 'macOS'
        run: |
          ./MyCppProject
